spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loadtest_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "qkrwntjs"
    hikari:
      maximum-pool-size: 100
  jpa:
    hibernate:
      ddl-auto: update # 애플리케이션 실행 시 스키마를 매번 새로 생성
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
