spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #username: "root"
    #password: "!@Adlqhdekfl12"
    hikari:
      maximum-pool-size: 25
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
 # data:
   # web:
     # pageable:
        #max-page-size: 1000000

logging:
  level:
    root : ERROR
    com.zaxxer.hikari: DEBUG
    org.hibernate.SQL: OFF
    #org.hibernate.type: trace

server:
  tomcat:
    mbeanregistry:
      enabled: true # Tomcat의 내부 메트릭을 JMX에 등록하여 Micrometer가 읽을 수 있게 함.

management:
  endpoints:
    web:
      exposure:
        #prometheus,health,metrics 등 모니터링에 필요한 엔드포인트 개방
        include: prometheus, health, info, metrics
  endpoint:
    prometheus:
      enabled: true