spring:
  application:
    name: load-test-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #username: "root"
    #password: "!@Adlqhdekfl12"
    hikari:
      maximum-pool-size: 25
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
 # data:
   # web:
     # pageable:
        #max-page-size: 1000000
logging:
  level:
    root : ERROR
    com.zaxxer.hikari: DEBUG
    org.hibernate.SQL: OFF
    #org.hibernate.type: trace
server:
  tomcat:
    accesslog:
      enabled: true
      directory: /tmp/tomcat-logs # 로그가 저장될 경로
      prefix: access_log
      suffix: .log
      # 어떤 정보를 남길지 패턴 지정 (IP, 요청시간, 응답코드, 소요시간 등)
      pattern: "%h %l %u %t \"%r\" %s %b %D"
    mbeanregistry:
      enabled: true # Tomcat의 내부 메트릭을 JMX에 등록하여 Micrometer가 읽을 수 있게 함.

management:
  endpoints:
    web:
      exposure:
        #prometheus,health,metrics 등 모니터링에 필요한 엔드포인트 개방
        include: prometheus, health, info, metrics
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}