spring:
  datasource:
    url: jdbc:h2:mem:testdb  # 메모리에 임시로 생성되는 DB
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true  # 브라우저로 DB 직접 보기 가능
  jpa:
    hibernate:
      ddl-auto: update  # 엔티티 변경 시 DB 테이블도 같이 자동 업데이트
    show-sql: true  # 실행되는 SQL 콘솔에 출력
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace