spring:
  datasource:
    url: jdbc:mysql://localhost:3306/loadtest_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "qkrwntjs"
  jpa:
    hibernate:
      ddl-auto: create # 애플리케이션 실행 시 스키마를 매번 새로 생성
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
